<div class="container">
    <div class="row">
        
            <h1 class="text-center login-title"> CAPACITACI&Oacute;N DE LA EDNOM 2014 </h1>
            <div class="account-wall">
                <img class="profile-img" src="<?php echo BASE_URL; ?>public/app/img/photo.jpg"
                    alt="">
                <form class="form-signin" role="form" action="<?php echo BASE_URL; ?>index.php/auth/auth/validar" method="POST" id="frmlogin" name="frmlogin">
                
                    <input type="password" class="form-control" id="clave" name="frmlogin[clave]" placeholder="Ingresar Contraseña" required>
                <button class="btn btn-lg btn-primary btn-block" type="submit">
                    Ingresar</button>
               
                <span class="clearfix"></span>
            
                </form>
                <div>Ingresar la clave del local</div>
            </div>
            
        
    </div>
</div>
            