<div class="container">
    <div class="panel panel-ecustom ui-shadow">
        <div class="panel-heading etitleprin">Envio Masivo</div>
        <div class="panel-body etitle">
            <select class="form-control" id="event_id" name="event">
                <option value="">SELECCIONE</option>
                <option value="1">Envio Masivo de Local</option>
                <option value="2">Envio Masivo de Aula</option>
                <option value="3">Envio Masivo de Ficha Electronica</option>
                <option value="4">Cartilla</option>
            </select>
            <input type="button" name="btnEnviar" id="btnEnviar_id" value="Enviar">
        </div>
    </div>
</div>